# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 18:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 8, 1, 18, 33, 11, 30908, tzinfo=utc), verbose_name='Production Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.CharField(default='test', max_length=150, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
