# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20160802_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='date',
            field=models.CharField(max_length=4, verbose_name='Production Date'),
        ),
    ]
