# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20160802_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(),
        ),
    ]
