# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_auto_20160802_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='slug',
            field=models.SlugField(),
        ),
    ]
