# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0003_auto_20160802_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='movie',
            field=models.ManyToManyField(related_name='actor', to='movies.Movie'),
        ),
    ]
